# Generated by Django 4.2.5 on 2023-11-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_fileupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
