# Generated by Django 4.2.5 on 2023-11-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="github_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_link",
            field=models.URLField(blank=True),
        ),
    ]
