# Generated by Django 4.2.5 on 2023-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QandA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
