# Generated by Django 4.2.5 on 2023-10-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QandA", "0002_alter_question_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_cat",
                to="QandA.tagcategory",
            ),
        ),
    ]
