# Generated by Django 4.2.5 on 2023-11-07 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("QandA", "0003_alter_tag_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["category"]},
        ),
        migrations.RemoveField(
            model_name="question",
            name="views",
        ),
        migrations.AddField(
            model_name="question",
            name="views",
            field=models.ManyToManyField(
                related_name="viewed", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
