# Generated by Django 4.2.5 on 2023-11-10 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("QandA", "0005_alter_answer_question_alter_answer_votes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="votes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="ans_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="viewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="votes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="Ques_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
