# Generated by Django 4.2.5 on 2023-11-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QandA", "0008_remove_answer_votes_remove_question_votes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="total_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="total_votes",
            field=models.IntegerField(default=0),
        ),
    ]
